export const DATA_REQUESTED = "DATA_REQUESTED";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_LOADING = "DATA_LOADING";
export const DATA_LOADING_FAILED = "DATA_LOADING_FAILED";
export const FETCH_DATA = "FETCH_DATA";
export const UPDATE_DATA = "UPDATE_DATA";